version: '3.3'
services:
  client:
    container_name: project-blue-frame-client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
#    links:
#      - "server:server"
  server:
    container_name: project-blue-frame-server
    build:
      context: ./server
      dockerfile: Dockerfile
    # volumes:
    #   - './server:/app'
    #   - '/app/node_modules'
    ports:
      - '5000:5000'
    links:
      - mongodb
    networks:
      - mongo-compose-network
  mongodb:
    container_name: project-blue-frame-mongo
    image: andresvidal/rpi3-mongodb3
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
      - dbcfg:/data/configdb
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge
volumes:
    db:
    dbcfg:
